//
//  FormModel.swift
//  Covid19VOCAAi
//
//  Created by Omer Elimelech on 07/04/2020.
//  Copyright © 2020 Omer Elimelech. All rights reserved.
//

import Foundation

protocol LocalizedEnum {
    func localizedString() -> String
    static var allValues: [LocalizedEnum] {
        get
    }
    var englishValue : String {get}
}
class FormModel: NSObject {
    
    let genderDataSource = Gender.allValues
    
    var countryDataSource : [String]{
        return countriesArray()
    }
    let smokeDataSource = SmokeSatus.allValues
    var diagnoseDataSource = Diagnoses.allValues
    let currentStatusDataSource = CurrentStatus.allValues
    var areYouDisgnoseDataSource = YesNo.allValues
    var symptomsDataSource = Sympthoms.allValues
    
    
    func sendForm(withJson json: [String: Any], completion: @escaping completion){
        APIManager.shared.sendReport(params: json, completion: completion)
    }
}

extension FormModel {

    func countriesArray() -> [String]{
        return englishCountries
        guard let code = languageCode() else {return []}
        switch code {
        case "en":
            return englishCountries
        case "he":
            return hebrewCountries.sorted(by: {$0 < $1})
        default:
            return []
        }
    }
    
    
}

extension FormModel{
    private var englishCountries : [String]{
        return [
            "Afghanistan",
            "Albania",
            "Algeria",
            "American Samoa",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antarctica",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas (the)",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia (Plurinational State of)",
            "Bonaire, Sint Eustatius and Saba",
            "Bosnia and Herzegovina",
            "Botswana",
            "Bouvet Island",
            "Brazil",
            "British Indian Ocean Territory (the)",
            "Brunei Darussalam",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cayman Islands (the)",
            "Central African Republic (the)",
            "Chad",
            "Chile",
            "China",
            "Christmas Island",
            "Cocos (Keeling) Islands (the)",
            "Colombia",
            "Comoros (the)",
            "Congo (the Democratic Republic of the)",
            "Congo (the)",
            "Cook Islands (the)",
            "Costa Rica",
            "Croatia",
            "Cuba",
            "Curaçao",
            "Cyprus",
            "Czechia",
            "Côte d'Ivoire",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic (the)",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Falkland Islands (the) [Malvinas]",
            "Faroe Islands (the)",
            "Fiji",
            "Finland",
            "France",
            "French Guiana",
            "French Polynesia",
            "French Southern Territories (the)",
            "Gabon",
            "Gambia (the)",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guadeloupe",
            "Guam",
            "Guatemala",
            "Guernsey",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Heard Island and McDonald Islands",
            "Holy See (the)",
            "Honduras",
            "Hong Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran (Islamic Republic of)",
            "Iraq",
            "Ireland",
            "Isle of Man",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jersey",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Korea (the Democratic People's Republic of)",
            "Korea (the Republic of)",
            "Kuwait",
            "Kyrgyzstan",
            "Lao People's Democratic Republic (the)",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macao",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands (the)",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Micronesia (Federated States of)",
            "Moldova (the Republic of)",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands (the)",
            "New Caledonia",
            "New Zealand",
            "Nicaragua",
            "Niger (the)",
            "Nigeria",
            "Niue",
            "Norfolk Island",
            "Northern Mariana Islands (the)",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine, State of",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines (the)",
            "Pitcairn",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Republic of North Macedonia",
            "Romania",
            "Russian Federation (the)",
            "Rwanda",
            "Réunion",
            "Saint Barthélemy",
            "Saint Helena, Ascension and Tristan da Cunha",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Martin (French part)",
            "Saint Pierre and Miquelon",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Sint Maarten (Dutch part)",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Georgia and the South Sandwich Islands",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan (the)",
            "Suriname",
            "Svalbard and Jan Mayen",
            "Sweden",
            "Switzerland",
            "Syrian Arab Republic",
            "Taiwan (Province of China)",
            "Tajikistan",
            "Tanzania, United Republic of",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tokelau",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks and Caicos Islands (the)",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates (the)",
            "United Kingdom of Great Britain and Northern Ireland (the)",
            "United States Minor Outlying Islands (the)",
            "United States of America (the)",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Venezuela (Bolivarian Republic of)",
            "Viet Nam",
            "Virgin Islands (British)",
            "Virgin Islands (U.S.)",
            "Wallis and Futuna",
            "Western Sahara",
            "Yemen",
            "Zambia",
            "Zimbabwe",
            "Åland Islands"
        ];
        
    }
    private var hebrewCountries: [String] {
        return ["אפגניסטן",
        "אלבניה",
        "אלג'יריה",
        "סמואה האמריקנית",
        "אנדורה",
        "אנגולה",
        "אנגווילה",
        "אנטארקטיקה",
        "אנטיגואה וברבודה",
        "ארגנטינה",
        "ארמניה",
        "ארובה",
        "אוסטרליה",
        "אוסטריה",
        "אזרבייג'ן",
        "איי בהאמה",
        "בחריין",
        "בנגלדש",
        "ברבדוס",
        "בלארוס",
        "בלגיה",
        "בליז",
        "בנין",
        "ברמודה",
        "בוטן",
        "בוליביה (מדינת פלורינציה)",
        "בונייר, סנט אוסטטיוס וסבא",
        "בוסניה והרצגובינה",
        "בוצואנה",
        "האי בובוט",
        "ברזיל",
        "הטריטוריה הבריטית באוקיאנוס ההודי (The)",
        "ברוניי דארוסלאם",
        "בולגריה",
        "בורקינה פאסו",
        "בורונדי",
        "קאבו ורדה",
        "קמבודיה",
        "קמרון",
        "קנדה",
        "איי קיימן (ה)",
        "הרפובליקה המרכז אפריקאית",
        "צ'אד",
        "צ'ילה",
        "חרסינה",
        "אי חג המולד",
        "איי קוקוס (קילינג) (האי)",
        "קולומביה",
        "קומורו (ה)",
        "קונגו (הרפובליקה הדמוקרטית של המדינה)",
        "קונגו (ה)",
        "איי קוק (ה)",
        "קוסטה ריקה",
        "קרואטיה",
        "קובה",
        "קוראסאו",
        "קפריסין",
        "צ'כיה",
        "חוף השנהב",
        "דנמרק",
        "ג'יבוטי",
        "דומיניקה",
        "הרפובליקה הדומיניקנית (ה)",
        "אקוודור",
        "מצרים",
        "אל סלבדור",
        "גיניאה המשוונית",
        "אריתריאה",
        "אסטוניה",
        "אתיופיה",
        "איי פוקלנד (ה) [מלווינוס]",
        "איי פארו (ה)",
        "פיג'י",
        "פינלנד",
        "צרפת",
        "גיאנה הצרפתית",
        "פולינזיה הצרפתית",
        "שטחי דרום צרפת (ה)",
        "גבון",
        "גמביה (ה)",
        "ג'ורג'יה",
        "גרמניה",
        "גאנה",
        "גיברלטר",
        "יוון",
        "גרינלנד",
        "גרנדה",
        "גוואדלופ",
        "גואם",
        "גואטמלה",
        "גרנזי",
        "גינאה",
        "גינאה ביסאו",
        "גיאנה",
        "האיטי",
        "איי הרד ואיי מקדונלד",
        "הכס הקדוש ()",
        "הונדורס",
        "הונג קונג",
        "הונגריה",
        "איסלנד",
        "הודו",
        "אינדונזיה",
        "איראן (הרפובליקה האיסלאמית של)",
        "עירק",
        "אירלנד",
        "האי מאן",
        "ישראל",
        "איטליה",
        "ג'מייקה",
        "יפן",
        "ג'רזי",
        "ירדן",
        "קזחסטן",
        "קניה",
        "קיריבטי",
        "קוריאה (הרפובליקה העממית הדמוקרטית של)",
        "קוריאה (הרפובליקה של)",
        "כווית",
        "קירגיזסטן",
        "הרפובליקה הדמוקרטית העממית של לאו",
        "לטביה",
        "לבנון",
        "לסוטו",
        "ליבריה",
        "לוב",
        "ליכטנשטיין",
        "ליטא",
        "לוקסמבורג",
        "מקאו",
        "מדגסקר",
        "מלאווי",
        "מלזיה",
        "האיים המלדיביים",
        "מאלי",
        "מלטה",
        "איי מרשל (ה)",
        "מרטיניק",
        "מאוריטניה",
        "מאוריציוס",
        "מיוט",
        "מקסיקו",
        "מיקרונזיה (המדינות הפדרליות של)",
        "מולדובה (הרפובליקה של)",
        "מונקו",
        "מונגוליה",
        "מונטנגרו",
        "מונטסראט",
        "מרוקו",
        "מוזמביק",
        "מיאנמר",
        "נמיביה",
        "נאורו",
        "נפאל",
        "הולנד",
        "קלדוניה החדשה",
        "ניו זילנד",
        "ניקרגואה",
        "ניז'ר ​​(ה)",
        "ניגריה",
        "ניואה",
        "האי נורפולק",
        "איי מריאנה הצפוניים (ה)",
        "נורווגיה",
        "עומאן",
        "פקיסטן",
        "פלאו",
        "פלסטין, מדינת",
        "פנמה",
        "פפואה גינאה החדשה",
        "פרגוואי",
        "פרו",
        "הפיליפינים (ה)",
        "פיטקרן",
        "פולין",
        "פורטוגל",
        "פוארטו ריקו",
        "קטאר",
        "רפובליקת צפון מקדוניה",
        "רומניה",
        "הפדרציה הרוסית",
        "רואנדה",
        "איחוד",
"סנט ברתלמי","סנט הלנה, ההתעלות וטריסטן דה קונהה",
"סנט קיטס ונביס",
"סנט לוסיה",
"סנט מרטין (חלק צרפתי)",
"סיינט פייר ומיקלון",
"וינסנט הקדוש ו ה - גרנידיים",
"סמואה",
"סן מרינו",
"סאו טומה ופרינסיפה",
"ערב הסעודית",
"סנגל",
"סרביה",
"סיישל",
"סיירה לאון",
"סינגפור",
"סנט מרטן (חלק הולנדי)",
"סלובקיה",
"סלובניה",
"איי שלמה",
"סומליה",
"דרום אפריקה",
"דרום ג'ורג'יה ואיי סנדוויץ 'דרום",
"דרום סודן",
"ספרד",
"סרי לנקה",
"סודן (ה)",
"סורינאם",
"שבדיה",
"שוויץ",
"הרפובליקה הערבית של סוריה",
"טייוואן (מחוז סין)",
"טג'יקיסטן",
"טנזניה, הרפובליקה המאוחדת של",
"תאילנד",
"טימור-לסטה",
"ללכת",
"טוקלאו",
"טונגה",
"טרינידד וטובגו",
"תוניסיה",
"טורקיה",
"טורקמניסטן",
"איי הטורקים וקוקוס (ה)",
"טובאלו",
"אוגנדה",
"אוקראינה",
"איחוד האמירויות הערביות",
"הממלכה המאוחדת של בריטניה וצפון אירלנד (ה)",
"האיים הקטנים של ארצות הברית הקטנות",
"ארה\"ב",
"אורוגוואי",
"אוזבקיסטן",
"ונואטו",
"ונצואלה (הרפובליקה הבוליברית)",
"ויאטנם",
"איי הבתולה (בריטניה)",
"איי הבתולה (ארה\"ב)",
"וואליס ופוטונה",
"סהרה המערבית",
"תימן",
"זמביה",
"זימבבואה",
"איי אלנד"]
    }
}
